dataset:
  observation_fieldnames:
     - index
     - sentence
     - lemma_sentence
     - upos_sentence
     - xpos_sentence
     - morph
     - head_indices
     - governance_relations
     - secondary_relations
     - extra_info
     - langs
     - embeddings
  corpus:
    root: ../datasets/calcs_english-hinglish
    train_path: train.conllu
    dev_path: dev.conllu
    test_path: test.conllu 
    inference_path: dev_en.txt
    use_translit: false
  embeddings:
    type: token #(token,subword)
    root: ../embeddings/qwen
    train_path: train_en.hdf5
    dev_path: dev_en.hdf5
    test_path: test_en.hdf5
    inference_path: calcs.hdf5
  edges:
    root: ../edges/qwen
    inference_path: en_dev_en_random-4.pkl 
  keys:
    train: ['en']
    dev: ['en']
    test: ['en']
    inference: ['en']
  batch_size: 8
model:
  hidden_dim: 3584 # ELMo hidden dim
  #embedding_dim: 1024 # ELMo word embedding dim
  model_type: GPT-disk # BERT-disk, ELMo-disk, 
  use_disk: True
  model_layer: 27 # BERT-base: (1,...,12); ELMo: (1,2,3)
  backbone_model: Qwen/Qwen2.5-7B
probe:
  task_signature: word_pair # word, word_pair
  task_name: parse-distance
  maximum_rank: 128
  psd_parameters: True
  diagonal: False
  params_path: multi_predictor.params
probe_training:
  epochs: 30
  loss: L1
reporting:
  root: ../probing_outputs/qwen
  observation_paths:
    train_path: train.observations
    dev_path: dev.observations
    test_path: test.observations
  prediction_paths:
    train_path: train.predictions
    dev_path: dev.predictions
    test_path: test.predictions
  reporting_methods:
    - spearmanr
      #- image_examples
    - uuas
    - proj_acc
    - adj_acc
